### ISSUE TITLE
Definition of the use case groups

### ISSUE THREAD

**Issue by gwemon** [i-adopt/usecase_analysis#1]
These groups are the "codes" referred to by Anu in her first analysis. We've agreed to call them "Use case groups" to help communication. They will be used to group the user stories submitted to us.

**Comment by gwemon** [comment]
@kitchenprinzessin3880 and I have come up with a set of use case groups and their definitions. 
Comments welcome from all but in particular @mabablue @SirkoS @mariutzica

**Comment by mabablue** [comment]
I am really happy with the groupings

**Comment by SirkoS** [comment]
*Not sure if to comment here or in the Google Doc, but as an IT guy I prefer Github ,-)*

Edit: created separate issues for all comments. Links provided below.

#3 From my perspective (2) "data integration and analysis" and (3) "data aggregation and product development" are pretty much the same. The product in the sense of (3) may also be the analysis of (2) in a more abstract sense. So I'd suggest to have (description of the second entry needs to be refined, I guess):

ID | use case group name | description
-- | -- | --
2 | data integration | Merge data from multiple heterogeneous sources
3 | data derivation | create new data (product or analysis) based on a given dataset

---

#4 We need to make the distinction between (1) "terminology management" and (7) "semantic modelling" clearer in my opinion. I guess the intention of (7) is to have a single identifier for a complex context (measured concentration of X at depth Y in medium Z". On the other hand, (1) is concerned with providing the terms for X, Y, and Z. I see the difference between both, but from my (outside) view both descriptions are to close right now.

---

#5 There are a few use cases in [Gwen's proposal](https://docs.google.com/spreadsheets/d/1nzd3vKzqztN8Atv0qCC7N-e71Ev1aSBmg-LrGbNDbEY/edit#gid=0) that are missing here. Although we might not have a user story to support each of them, I still think they should be included:
- semantic annotation was split between data and metadata annotations. I think this has some implications on the terms and structures that a vocabulary needs to support (basically the next subtask)
- "data selection through faceted search". I'm currently working in that field and to me its different from "semantic search"
- "data exploration through visualization". Here I'm a little unsure. I might see this as an additional interface to semantic search. On the other hand, there might be other requirements for visual representations that are better covered in a separate use case.
- "provision of tools and services". Here I think this does not warrant a separate use case, as this is more about support of the other use cases.
The other use cases are covered, I guess.

---

#6 Is there a decision to abolish the higher orders of abstractions as listed in Gwen proposal? To me they provide an additional level of structuring, so I'd like to keep them in some form. Given the current "use case group names" as listed in the mentioned file, I suggest the following:

1. Terminology / vocabulary management: (1), (7), (8)
2. Data discovery: (4) + faceted search + exploration through visualization
3. annotation: (5), (9) + the distinction into data and metadata annotations
4. data integration: (2), (3), (6), 

---

~~PS: the terms "use case", "user story", "use case group" should be defined in our glossary. I'm currently slightly confused about the conventions about their meaning.~~ -> [use case group](https://github.com/i-adopt/glossary/issues/8)

~~PPS: it might be worthwhile to split my comments into multiple issues. If people agree I'd split them up later on.~~ done

**Comment by gwemon** [comment]
@SirkoS Thank you very much for your comments. Yes, I think it would be easier to manage if you could split them into separate issue tickets.

**Comment by mabablue** [comment]
@SirkoS I very much support to keep data integration and data derivation separately, but not sure at which level.  probably data manipulation could be the use case group and data integration and data derivation two use cases of it. Data annotation was already planned to have as use case group while data annotation and metadata annotation would be the associated use cases see https://docs.google.com/spreadsheets/d/1sYh0lIlT9xi9hAmn_6hqr32bKjjphU2UU5IZ131xsbk/edit#gid=59820149 tab user story/use case. I agree we need definitions for these concepts: user story/use case/use case group. But we have already started to define them in https://github.com/i-adopt/glossary only use case group is missing. Please all check the definitions there and adust.

**Comment by SirkoS** [comment]
> @SirkoS Thank you very much for your comments. Yes, I think it would be easier to manage if you could split them into separate issue tickets.

**done**



> Data annotation was already planned to have as use case group while data annotation and metadata annotation would be the associated use cases see https://docs.google.com/spreadsheets/d/1sYh0lIlT9xi9hAmn_6hqr32bKjjphU2UU5IZ131xsbk/edit#gid=59820149 tab user story/use case.

I think I missed to look at that table. I'll have to think about it. Maybe this already solves some of the comments I mentioned before.

**Comment by graybeal** [comment]
> @kitchenprinzessin3880 and I have come up with a set of use case groups and their definitions. See [use_case_groups_definitions.csv](https://github.com/i-adopt/usecase_analysis/blob/master/use_case_groups_definitions.csv)
> Comments welcome from all but in particular @mabablue @SirkoS @mariutzica

This link did not work when I clicked on it. Perhaps edit the comment above to fix?

**Comment by gwemon** [comment]
@graybeal It looks like the file has been removed. I will fix this.

**Comment by gwemon** [comment]
@graybeal I have removed the link to the file in my original comment at the top of this thread. Please look at the file use_case_groups.csv in the usecase_analysis repository to see the latest User Case Groupings and their definitions.

**Comment by graybeal** [comment]
Thanks Gwen. Those ([link](https://github.com/i-adopt/usecase_analysis/blob/master/use_case_groups.csv)) look well thought through. I wouldn't want to put much more effort into them unless you need to refine them to achieve the end goals.  (Not meant to cut off discussion, just to point out that later evolution is always possible if it is needed.)

Note the definitions mentioned here:
> I agree we need definitions for these concepts: user story/use case/use case group. But we have already started to define them in https://github.com/i-adopt/glossary only use case group is missing. Please all check the definitions there and adust.

aren't where this says they are either. I think at this point they are in the definitions linked above in this comment.

**Comment by gwemon** [comment]
@graybeal I agree that the objective of this ticket is now complete and it can be closed. Should  anybody have any issues with either the list of use cases or their definitions or groupings then it will need to be discussed in a new issue ticket.
