### ISSUE TITLE
User case and use case groups identifiers

### ISSUE THREAD

**Issue by gwemon** [i-adopt/usecase_analysis#11]
Could we use non-numerical identifiers for the use cases and the use case groups? I would also recommend having identifiers for the use cases that are independent from the group ID. This is to leave us flexibility if we were to decide to group the use cases in some other ways. My preference would be to have the 4 groups: G1, G2, G4, G4 for the upper level groups; and UC1,...,UC14 for the user cases.

**Comment by mabablue** [comment]
I updated the csv file with the suggested IDs and close this issue
