### ISSUE TITLE
Upper use case groups

### ISSUE THREAD

**Issue by SirkoS** [i-adopt/usecase_analysis#6]
Is there a decision to abolish the higher orders of abstractions as listed in [Gwen's proposal](https://docs.google.com/spreadsheets/d/1nzd3vKzqztN8Atv0qCC7N-e71Ev1aSBmg-LrGbNDbEY/edit#gid=0)? To me they provide an additional level of structuring, so I'd like to keep them in some form. Given the current "use case group names" as listed in the mentioned file, I suggest the following:

1. Terminology / vocabulary management: (1), (7), (8)
2. Data discovery: (4) + faceted search + exploration through visualization
3. annotation: (5), (9) + the distinction into data and metadata annotations
4. data integration: (2), (3), (6),

**Comment by mariutzica** [comment]
I would like to thumbs this up multiple times, but GitHub does not allow this. I absolutely agree, and I think this would be extremely helpful. I would suggest going even one step further and "ordering" these categories into a logical workflow whenever they are presented:

1. Terminology / vocabulary generation/gathering and management
2. Resource annotation
3. Data discovery and exploration
4. Data manipulation and integration.

**Comment by SirkoS** [comment]
as per discussion 2020-03-18:

*accepted*
